name: cherry_block
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

  
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  logger: ^2.6.1
  shared_preferences: ^2.5.3
  provider: ^6.1.5+1
  nfc_manager: ^4.0.2
  sqflite: ^2.4.2
  path: ^1.9.1
  url_launcher: ^6.3.2
  flutter_rating_bar: ^4.0.1
  icons_launcher: ^2.1.7  
  mobile_scanner: ^7.1.3
  excel: ^4.0.3  
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  
  ##firebase packages
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/Logo.webp
    - lib/services/rating.json
    - assets/logo2.png



